name: Deploy Next.js to Azure Web App

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '22.x'
  AZURE_WEBAPP_NAME: 'nerone-site'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create deployment package
        run: |
          # Crea una cartella per il deploy senza node_modules
          mkdir deploy
          
          # Copia tutti i file del progetto tranne node_modules
          rsync -av --exclude=node_modules --exclude=.git --exclude=.next . deploy/
          
          # Assicurati che i file essenziali ci siano
          ls -la deploy/
          echo "=== PACKAGE.JSON CONTENT ==="
          cat deploy/package.json

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure Azure Web App for build
        run: |
          az webapp config appsettings set \
            --resource-group "NeroneBot" \
            --name "${{ env.AZURE_WEBAPP_NAME }}" \
            --settings \
              SCM_DO_BUILD_DURING_DEPLOYMENT=true \
              ENABLE_ORYX_BUILD=true \
              NODE_VERSION="${{ env.NODE_VERSION }}"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          package: './deploy'
